name: Feature request
description: Suggest a new feature or improvement
labels: [enhancement]
projects: ["jathavaan/7"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: What's missing or annoying today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Where does this apply?
      options:
        - Client (React app)
        - Server (API)
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (optional)
    validations:
      required: false
